<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>L O G I N</h1>
<form action="/login/auth" method="post">
    <div class="form">
        Login: <input type="text">
        Password: <input type="password">
        <input type="submit" value="Login">
    </div>
</form>
</body>
<style>
    .form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
</style>
</html>
