<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>L O G I N</h1>
<form action="/login/auth" method="post">

    <div class="form">

        <?php
        if (!empty($errors = $this->errors)) { ?>
            <div class="errors">
                <?php
                foreach ($errors as $error) {
                    echo $error . "<br>";
                }
                ?>
            </div>
        <?php } ?>


        Login (e-mail): <input class="input" type="text" name="email">
        Password : <input class="input" type="password" name="password">
        <input type="submit" value="Login">
    </div>
</form>
<div class="exit">
    <a href="Index/exit">Exit</a>
</div>
</body>
<style>
    .exit {
        font-size: 24px;
        font-weight: bold;
        margin-top: 20px;
        text-align: center;
    }
    .form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .errors {
        margin-bottom: 30px;
        border: red 2px solid;
    }
    h1 {
        text-align: center;
    }
</style>
</html>
