<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>R E G I S T E R</h1>
<form action="/register/register" method="post">
    <div class="form">
        <?php
        if (!empty($errors = $this->errors)) {
            foreach ($errors as $error) {
                echo $error . "<br>";
            }
        }
        ?>
        Name: <input class="input" type="text" name="name">
        E-mail: <input class="input" type="text" name="email">
        Password (длина пароля не менее 4х символов): <input class="input" type="password" name="password">
        Password: (Повторите пароль) <input class="input" type="password" name="password_2">
        <input type="submit" value="Register">
    </div>
</form>
</body>
<style>
    .form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .input {
        margin-top: 5px;
        margin-bottom: 20px;
    }
    h1 {
        text-align: center;
    }
</style>
</html>